<a href="https://colab.research.google.com/github/simoneminorr/GH-demo/blob/main/notebooks/06_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Installing & Importing Packages

`numpy` is the first Python package we will be using. External packages not built into Python usually have to be (1) installed and (2) imported.

### Installing

To install any package into your current Google Colab session, use the `!pip` command like this:
```
!pip install numpy
```
However, `numpy` is such a common package it comes pre-installed here.

### Importing
Once a package is installed into your system, it must be imported into any Python code using the `import` command:
```
import numpy
```
### Import Aliases
Python also allows import statements to declare an alias for referencing the package. It is a common practice among `numpy` users to import it as `np` like this:
```
import numpy as np
```

## Basic NumPy Array Functionality

In [1]:
import numpy as np

In [ ]:
np.

In [2]:
z = np.ones(10)
z
#gives you 10 ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [3]:
#to see the shape/dimension
z.shape

(10,)

In [4]:
#going to look for space in a range
z = np.linspace(2, 10, 5)         # go from 2 to 10, with 5 elements
z

array([ 2.,  4.,  6.,  8., 10.])

In [5]:
a_list = [1,2,3,4,5,6,7]
#make an array out of the list we made
z = np.array([a_list])
z
#now sees them as integers not floats

array([[1, 2, 3, 4, 5, 6, 7]])

In [6]:
type(z)

numpy.ndarray

In [7]:
b_list = [[9,8,7,6,5,4,3],[1,2,3,4,5,6,7]]      # 2-dimensional array; list containing 2 lists
z = np.array([b_list]) #notice each has 7 values so they almost line up as they would in a 2 dimensional array
z

array([[[9, 8, 7, 6, 5, 4, 3],
        [1, 2, 3, 4, 5, 6, 7]]])

In [8]:
z.shape #1 record with 2 subrecords with 7 values under each

(1, 2, 7)

In [9]:
# Sort an array

x = np.array([2, 1, 4, 3, 5])
np.sort(x)
#gives you a new array with the conditions I asked for which was for it to be sorted from least to greatest

array([1, 2, 3, 4, 5])

In [10]:
z = np.array([1, 2, 3, 4, 5])

In [11]:
# Filter the array
z < 3 #give me z where everything is less than 3 out of all the things in the array; outputs true if it is less than 3 and false for those that aren't (boolean)

array([ True,  True, False, False, False])

In [12]:
z > 3

array([False, False, False,  True,  True])

In [13]:
# Apply a mask to an array
z[z > 3]

array([4, 5])

In [15]:
# Adding and combining arrays; adds down the column/down the index

a_array = np.array([1,2,3,4,5])
b_array = np.array([6,7,8,9,10])

In [16]:
a_array + b_array #added up two rows

array([ 7,  9, 11, 13, 15])

In [17]:
a_array + 30 #adds 30 to each value

array([31, 32, 33, 34, 35])

In [18]:
a_array * b_array

array([ 6, 14, 24, 36, 50])

In [19]:
a_array * 10

array([10, 20, 30, 40, 50])

## Images are Numerical Data

In [20]:
!pip install scikit-image matplotlib

In [21]:
import numpy as np
from skimage import io

photo = io.imread('hotel.jpg') #doesn't work for us because we don't have the image, however a photo is just a multidimensional array
type(photo) #can tell the photos to invert, flip, etc. which is how filters work (formulas to use inside a numerical calculator to apply to data)

FileNotFoundError: ignored

In [ ]:
photo.shape

In [ ]:
import matplotlib.pyplot as plt
plt.imshow(photo)

In [ ]:
plt.imshow(photo[::-1])

In [ ]:
plt.imshow(photo[:, ::-1])

In [ ]:
plt.imshow(photo[200:400, 300:500])

In [ ]:
plt.imshow(photo[::2, ::2])

In [ ]:
# Get the sin of all three channels of each pixel value

photo_sin = np.sin(photo)
photo_sin

In [ ]:
# Other built-in statistical functions

print(np.sum(photo))
print(np.prod(photo))
print(np.mean(photo))
print(np.std(photo))
print(np.var(photo))
print(np.min(photo))
print(np.max(photo))

In [ ]:
# Search every value in the array, and when a value is above 100, replace it with 255.
# Where it isn't above 100, replace with 0.

photo_masked = np.where(photo > 100, 255, 0)

In [ ]:
plt.imshow(photo_masked)

In [ ]:
# Both filter the values of the array and transpose its axes.
# Switches rows and columns.

plt.imshow(photo[:,:,0].T)